### ISSUE TITLE
pip install overwrites DRF and installs old version of django-parler-rest

### ISSUE THREAD

**Issue by anyong** [edoburu/django-parler-rest#2]
Just an FYI, it would be good to get this fixed since the code in this package seems to be up to date for DRF 3+ now. I just spent a while trying to figure out why my site broke after installing it!

**Comment by vdboor** [comment]
Thanks for reporting this, it was completely missed when the pull request was merged for DRF support. The latest git is fixed now.

**Comment by cho-is** [comment]
Still having this issue
