### ISSUE TITLE
Push 1.3a1 to PyPI?

### ISSUE THREAD

**Issue by akx** [edoburu/django-parler-rest#5]
1.3a1 is not in PyPI.

Could we get an official release of it? :)

**Comment by vdboor** [comment]
Sure! Just wondering, is this package working properly for you? I haven't been able to test this yet with an existing production site, hence the release wasn't uploaded.

**Comment by akx** [comment]
Worked fine for reading at the very least!

Didn't have the time to test writing though. I'll try to get back to you on that!

**Comment by akx** [comment]
Writing (POSTing) seems to work fine too. :)

**Comment by vdboor** [comment]
I've added a v1.3b1 to pypi

I've just merged your test suite, and it does seem to fail creating some languages. This could be something I've broken, but it's worth investigating it.

**Comment by akx** [comment]
Cheers, this has probably been obviated by v1.3 having been released!

Thanks for the work you've put into Parler and this! :)))
